#!/bin/bash
function STDERR () {
  cat - 1>&2
}

if echo $@ | grep 'verbose' 2>&1 /dev/null
then
# verbose
echo "$(basename $0) $@"
echo "httperf: warning: open file limit > FD_SETSIZE; limiting max. # of open files to FD_SETSIZE" | STDERR
echo "RT0:164.054871	200"
sleep .1
echo "Connection lifetime = 164.5"
sleep .1
echo "RT1:532.962084	200"
sleep .1
echo "Connection lifetime = 532.5"
sleep .1
echo "RT2:257.379055	200"
sleep .1
echo "Connection lifetime = 257.5"
sleep .1
echo "RT3:440.126896	200"
sleep .1
echo "Connection lifetime = 440.5"
sleep .1
echo "RT4:660.751104	200"
sleep .1
echo "Connection lifetime = 660.5"
sleep .1
echo "RT5:139.378786	200"
sleep .1
echo "Connection lifetime = 139.5"
sleep .1
echo "RT6:144.936085	200"
sleep .1
echo "Connection lifetime = 144.5"
sleep .1
echo "RT7:418.461084	200"
sleep .1
echo "Connection lifetime = 418.5"
sleep .1
echo "RT8:255.043030	200"
sleep .1
echo "Connection lifetime = 255.5"
sleep .1
echo "RT9:160.689831	200"
sleep .1
echo "Connection lifetime = 160.5"
sleep .1
echo "RT10:428.452015	200"
sleep .1
echo "Connection lifetime = 428.5"
sleep .1
echo "RT11:153.122187	200"
sleep .1
echo "Connection lifetime = 153.5"
sleep .1
echo "RT12:695.820808	200"
sleep .1
echo "Connection lifetime = 695.5"
sleep .1
echo "RT13:161.413193	200"
sleep .1
echo "Connection lifetime = 161.5"
sleep .1
echo "RT14:165.160894	200"
sleep .1
echo "Connection lifetime = 165.5"
sleep .1
echo "RT15:160.202980	200"
sleep .1
echo "Connection lifetime = 160.5"
sleep .1
echo "reply-rate = 3.2"
sleep .1
echo "RT16:206.342936	200"
sleep .1
echo "Connection lifetime = 206.5"
sleep .1
echo "RT17:172.633171	200"
sleep .1
echo "Connection lifetime = 172.5"
sleep .1
echo "RT18:392.226934	200"
sleep .1
echo "Connection lifetime = 392.5"
sleep .1
echo "RT19:152.445078	200"
sleep .1
echo "Connection lifetime = 152.5"
sleep .1
echo "RT20:143.802881	200"
sleep .1
echo "Connection lifetime = 143.5"
sleep .1
echo "RT21:135.888100	200"
sleep .1
echo "Connection lifetime = 135.5"
sleep .1
echo "RT22:391.423941	200"
sleep .1
echo "Connection lifetime = 391.5"
sleep .1
echo "RT23:142.564058	200"
sleep .1
echo "Connection lifetime = 142.5"
sleep .1
echo "RT24:139.175892	200"
sleep .1
echo "Connection lifetime = 139.5"
sleep .1
echo "RT25:146.286964	200"
sleep .1
echo "Connection lifetime = 146.5"
sleep .1
echo "RT26:385.911942	200"
sleep .1
echo "Connection lifetime = 385.5"
sleep .1
echo "RT27:500.527143	200"
sleep .1
echo "Connection lifetime = 500.5"
sleep .1
echo "RT28:290.349007	200"
sleep .1
echo "Connection lifetime = 290.5"
sleep .1
echo "RT29:141.918898	200"
sleep .1
echo "Connection lifetime = 141.5"
sleep .1
echo "RT30:291.085958	200"
sleep .1
echo "Connection lifetime = 291.5"
sleep .1
echo "RT31:137.889147	200"
sleep .1
echo "Connection lifetime = 137.5"
sleep .1
echo "RT32:288.292885	200"
sleep .1
echo "Connection lifetime = 288.5"
sleep .1
echo "RT33:138.436079	200"
sleep .1
echo "Connection lifetime = 138.5"
sleep .1
echo "RT34:284.863949	200"
sleep .1
echo "Connection lifetime = 284.5"
sleep .1
echo "RT35:283.437967	200"
sleep .1
echo "Connection lifetime = 283.5"
sleep .1
echo "RT36:149.239063	200"
sleep .1
echo "Connection lifetime = 149.5"
sleep .1
echo "reply-rate = 4.2"
sleep .1
echo "RT37:288.504124	200"
sleep .1
echo "Connection lifetime = 288.5"
sleep .1
echo "RT38:138.604879	200"
sleep .1
echo "Connection lifetime = 138.5"
sleep .1
echo "RT39:292.285919	200"
sleep .1
echo "Connection lifetime = 292.5"
sleep .1
echo "RT40:137.781143	200"
sleep .1
echo "Connection lifetime = 137.5"
sleep .1
echo "RT41:285.260916	200"
sleep .1
echo "Connection lifetime = 285.5"
sleep .1
echo "RT42:141.850948	200"
sleep .1
echo "Connection lifetime = 141.5"
sleep .1
echo "RT43:286.570072	200"
sleep .1
echo "Connection lifetime = 286.5"
sleep .1
echo "RT44:138.684034	200"
sleep .1
echo "Connection lifetime = 138.5"
sleep .1
echo "RT45:287.760973	200"
sleep .1
echo "Connection lifetime = 287.5"
sleep .1
echo "RT46:289.455891	200"
sleep .1
echo "Connection lifetime = 289.5"
sleep .1
echo "RT47:178.175211	200"
sleep .1
echo "Connection lifetime = 178.5"
sleep .1
echo "RT48:328.647852	200"
sleep .1
echo "Connection lifetime = 328.5"
sleep .1
echo "RT49:144.082069	200"
sleep .1
echo "Connection lifetime = 144.5"
sleep .1
echo "RT50:291.280031	200"
sleep .1
echo "Connection lifetime = 291.5"
sleep .1
echo "RT51:138.470888	200"
sleep .1
echo "Connection lifetime = 138.5"
sleep .1
echo "RT52:289.855957	200"
sleep .1
echo "Connection lifetime = 289.5"
sleep .1
echo "RT53:135.639191	200"
sleep .1
echo "Connection lifetime = 135.5"
sleep .1
echo "RT54:289.345026	200"
sleep .1
echo "Connection lifetime = 289.5"
sleep .1
echo "RT55:137.350798	200"
sleep .1
echo "Connection lifetime = 137.5"
sleep .1
echo "RT56:330.978155	200"
sleep .1
echo "Connection lifetime = 330.5"
sleep .1
echo "RT57:323.415041	200"
sleep .1
echo "Connection lifetime = 323.5"
sleep .1
echo "RT58:145.509005	200"
sleep .1
echo "Connection lifetime = 145.5"
sleep .1
echo "reply-rate = 4.4"
sleep .1
echo "RT59:294.952869	200"
sleep .1
echo "Connection lifetime = 294.5"
sleep .1
echo "RT60:142.269135	200"
sleep .1
echo "Connection lifetime = 142.5"
sleep .1
echo "RT61:138.293982	200"
sleep .1
echo "Connection lifetime = 138.5"
sleep .1
echo "RT62:388.613939	200"
sleep .1
echo "Connection lifetime = 388.5"
sleep .1
echo "RT63:140.385866	200"
sleep .1
echo "Connection lifetime = 140.5"
sleep .1
echo "RT64:294.457197	200"
sleep .1
echo "Connection lifetime = 294.5"
sleep .1
echo "RT65:139.772892	200"
sleep .1
echo "Connection lifetime = 139.5"
sleep .1
echo "RT66:303.258896	200"
sleep .1
echo "Connection lifetime = 303.5"
sleep .1
echo "RT67:141.956091	200"
sleep .1
echo "Connection lifetime = 141.5"
sleep .1
echo "RT68:298.655033	200"
sleep .1
echo "Connection lifetime = 298.5"
sleep .1
echo "RT69:136.940002	200"
sleep .1
echo "Connection lifetime = 136.5"
sleep .1
echo "RT70:688.719034	200"
sleep .1
echo "Connection lifetime = 688.5"
sleep .1
echo "RT71:140.038967	200"
sleep .1
echo "Connection lifetime = 140.5"
sleep .1
echo "RT72:138.895988	200"
sleep .1
echo "Connection lifetime = 138.5"
sleep .1
echo "RT73:417.140961	200"
sleep .1
echo "Connection lifetime = 417.5"
sleep .1
echo "RT74:145.699024	200"
sleep .1
echo "Connection lifetime = 145.5"
sleep .1
echo "RT75:141.577005	200"
sleep .1
echo "Connection lifetime = 141.5"
sleep .1
echo "RT76:416.074991	200"
sleep .1
echo "Connection lifetime = 416.5"
sleep .1
echo "RT77:142.570019	200"
sleep .1
echo "Connection lifetime = 142.5"
sleep .1
echo "RT78:143.624067	200"
sleep .1
echo "Connection lifetime = 143.5"
sleep .1
echo "reply-rate = 4.0"
sleep .1
echo "RT79:426.810026	200"
sleep .1
echo "Connection lifetime = 426.5"
sleep .1
echo "RT80:149.154902	200"
sleep .1
echo "Connection lifetime = 149.5"
sleep .1
echo "RT81:148.390055	200"
sleep .1
echo "Connection lifetime = 148.5"
sleep .1
echo "RT82:152.786016	200"
sleep .1
echo "Connection lifetime = 152.5"
sleep .1
echo "RT83:409.765005	200"
sleep .1
echo "Connection lifetime = 409.5"
sleep .1
echo "RT84:147.444010	200"
sleep .1
echo "Connection lifetime = 147.5"
sleep .1
echo "RT85:144.798994	200"
sleep .1
echo "Connection lifetime = 144.5"
sleep .1
echo "RT86:177.811861	200"
sleep .1
echo "Connection lifetime = 177.5"
sleep .1
echo "RT87:417.634010	200"
sleep .1
echo "Connection lifetime = 417.5"
sleep .1
echo "RT88:263.844967	200"
sleep .1
echo "Connection lifetime = 263.5"
sleep .1
echo "RT89:169.666052	200"
sleep .1
echo "Connection lifetime = 169.5"
sleep .1
echo "RT90:311.697006	200"
sleep .1
echo "Connection lifetime = 311.5"
sleep .1
echo "RT91:671.070099	200"
sleep .1
echo "Connection lifetime = 671.5"
sleep .1
echo "RT92:163.714886	200"
sleep .1
echo "Connection lifetime = 163.5"
sleep .1
echo "RT93:469.439983	200"
sleep .1
echo "Connection lifetime = 469.5"
sleep .1
echo "RT94:140.473127	200"
sleep .1
echo "Connection lifetime = 140.5"
sleep .1
echo "RT95:167.948961	200"
sleep .1
echo "Connection lifetime = 167.5"
sleep .1
echo "RT96:169.555902	200"
sleep .1
echo "Connection lifetime = 169.5"
sleep .1
echo "RT97:164.805174	200"
sleep .1
echo "Connection lifetime = 164.5"
sleep .1
echo "RT98:162.867785	200"
sleep .1
echo "Connection lifetime = 162.5"
sleep .1
echo "RT99:173.114061	200"
sleep .1
echo "Connection lifetime = 173.5"
sleep .1
echo "Maximum connect burst length: 1"
sleep .1
echo ""
sleep .1
echo "Connection lifetime histogram (time in ms):"
sleep .1
echo "             :"
sleep .1
echo "           135.5 2"
sleep .1
echo "           136.5 1"
sleep .1
echo "           137.5 3"
sleep .1
echo "           138.5 6"
sleep .1
echo "           139.5 3"
sleep .1
echo "           140.5 3"
sleep .1
echo "           141.5 4"
sleep .1
echo "           142.5 3"
sleep .1
echo "           143.5 2"
sleep .1
echo "           144.5 3"
sleep .1
echo "           145.5 2"
sleep .1
echo "           146.5 1"
sleep .1
echo "           147.5 1"
sleep .1
echo "           148.5 1"
sleep .1
echo "           149.5 2"
sleep .1
echo "             :"
sleep .1
echo "           152.5 2"
sleep .1
echo "           153.5 1"
sleep .1
echo "             :"
sleep .1
echo "           160.5 2"
sleep .1
echo "           161.5 1"
sleep .1
echo "           162.5 1"
sleep .1
echo "           163.5 1"
sleep .1
echo "           164.5 2"
sleep .1
echo "           165.5 1"
sleep .1
echo "             :"
sleep .1
echo "           167.5 1"
sleep .1
echo "             :"
sleep .1
echo "           169.5 2"
sleep .1
echo "             :"
sleep .1
echo "           172.5 1"
sleep .1
echo "           173.5 1"
sleep .1
echo "             :"
sleep .1
echo "           177.5 1"
sleep .1
echo "           178.5 1"
sleep .1
echo "             :"
sleep .1
echo "           206.5 1"
sleep .1
echo "             :"
sleep .1
echo "           255.5 1"
sleep .1
echo "             :"
sleep .1
echo "           257.5 1"
sleep .1
echo "             :"
sleep .1
echo "           263.5 1"
sleep .1
echo "             :"
sleep .1
echo "           283.5 1"
sleep .1
echo "           284.5 1"
sleep .1
echo "           285.5 1"
sleep .1
echo "           286.5 1"
sleep .1
echo "           287.5 1"
sleep .1
echo "           288.5 2"
sleep .1
echo "           289.5 3"
sleep .1
echo "           290.5 1"
sleep .1
echo "           291.5 2"
sleep .1
echo "           292.5 1"
sleep .1
echo "             :"
sleep .1
echo "           294.5 2"
sleep .1
echo "             :"
sleep .1
echo "           298.5 1"
sleep .1
echo "             :"
sleep .1
echo "           303.5 1"
sleep .1
echo "             :"
sleep .1
echo "           311.5 1"
sleep .1
echo "             :"
sleep .1
echo "           323.5 1"
sleep .1
echo "             :"
sleep .1
echo "           328.5 1"
sleep .1
echo "             :"
sleep .1
echo "           330.5 1"
sleep .1
echo "             :"
sleep .1
echo "           385.5 1"
sleep .1
echo "             :"
sleep .1
echo "           388.5 1"
sleep .1
echo "             :"
sleep .1
echo "           391.5 1"
sleep .1
echo "           392.5 1"
sleep .1
echo "             :"
sleep .1
echo "           409.5 1"
sleep .1
echo "             :"
sleep .1
echo "           416.5 1"
sleep .1
echo "           417.5 2"
sleep .1
echo "           418.5 1"
sleep .1
echo "             :"
sleep .1
echo "           426.5 1"
sleep .1
echo "             :"
sleep .1
echo "           428.5 1"
sleep .1
echo "             :"
sleep .1
echo "           440.5 1"
sleep .1
echo "             :"
sleep .1
echo "           469.5 1"
sleep .1
echo "             :"
sleep .1
echo "           500.5 1"
sleep .1
echo "             :"
sleep .1
echo "           532.5 1"
sleep .1
echo "             :"
sleep .1
echo "           660.5 1"
sleep .1
echo "             :"
sleep .1
echo "           671.5 1"
sleep .1
echo "             :"
sleep .1
echo "           688.5 1"
sleep .1
echo "             :"
sleep .1
echo "           695.5 1"
sleep .1
echo ""
sleep .1
echo "Total: connections 100 requests 100 replies 100 test-duration 24.869 s

Connection rate: 4.0 conn/s (248.7 ms/conn, <=1 concurrent connections)
Connection time [ms]: min 135.6 avg 248.7 max 695.8 median 169.5 stddev 137.2
Connection time [ms]: connect 0.1
Connection length [replies/conn]: 1.000

Request rate: 4.0 req/s (248.7 ms/req)
Request size [B]: 78.0

Reply rate [replies/s]: min 3.2 avg 3.9 max 4.4 stddev 0.5 (4 samples)
Reply time [ms]: response 239.3 transfer 9.3
Reply size [B]: header 1092.0 content 195954.0 footer 2.0 (total 197048.0)
Reply status: 1xx=0 2xx=100 3xx=0 4xx=0 5xx=0

CPU time [s]: user 0.01 system 0.04 (user 0.0% system 0.2% total 0.2%)
Net I/O: 774.1 KB/s (6.3*10^6 bps)

Errors: total 0 client-timo 0 socket-timo 0 connrefused 0 connreset 0
Errors: fd-unavail 0 addrunavail 0 ftab-full 0 other 0
"
exit 0
else
# not verbose
echo "$(basename $0) $@"
echo "httperf: warning: open file limit > FD_SETSIZE; limiting max. # of open files to FD_SETSIZE" | STDERR
echo "Maximum connect burst length: 0

Total: connections 1 requests 1 replies 1 test-duration 0.000 s

Connection rate: 4524.6 conn/s (0.2 ms/conn, <=1 concurrent connections)
Connection time [ms]: min 0.2 avg 0.2 max 0.2 median 0.5 stddev 0.0
Connection time [ms]: connect 0.1
Connection length [replies/conn]: 1.000

Request rate: 4524.6 req/s (0.2 ms/req)
Request size [B]: 62.0

Reply rate [replies/s]: min 0.0 avg 0.0 max 0.0 stddev 0.0 (0 samples)
Reply time [ms]: response 0.1 transfer 0.0
Reply size [B]: header 154.0 content 168.0 footer 0.0 (total 322.0)
Reply status: 1xx=0 2xx=0 3xx=0 4xx=1 5xx=0

CPU time [s]: user 0.00 system 0.00 (user 0.0% system 0.0% total 0.0%)
Net I/O: 1696.7 KB/s (13.9*10^6 bps)

Errors: total 0 client-timo 0 socket-timo 0 connrefused 0 connreset 0
Errors: fd-unavail 0 addrunavail 0 ftab-full 0 other 0
"
exit 0
fi
# vim: filetype=sh:
